name = "lajes-backend"
main = "src/index.ts"          # ou dist/index.js
compatibility_date = "2024-10-01"

# Se for usar domínios/rotas personalizadas (opcional)
# routes = [{ pattern = "api.seudominio.com/analisar", zone_name = "seudominio.com" }]

# Variáveis / bindings podem ir via dashboard ou secrets
